// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MultilingualExtensionWindows
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidMultilingualExtensionWindowsPackageString = "a976f7e6-3c4b-4234-80aa-f8f5400443c0";
        public static Guid guidMultilingualExtensionWindowsPackage = new Guid(guidMultilingualExtensionWindowsPackageString);

        public const string guidMultilingualExtensionWindowsPackageCmdSetString = "e86c9f19-293d-49ab-8b5b-f4039e5193db";
        public static Guid guidMultilingualExtensionWindowsPackageCmdSet = new Guid(guidMultilingualExtensionWindowsPackageCmdSetString);

        public const string guidImagesString = "e1e1d1d1-81ef-47fb-9d53-4190d8b4edab";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int MyGroupForSubMenuProjectPad = 0x1021;
        public const int CommandIdShowSettings = 0x0100;
        public const int CommandIdUpdateFiles = 0x0101;
        public const int CommandIdTranslateFiles = 0x0102;
        public const int CommandIdExportFiles = 0x0103;
        public const int CommandIdImportFiles = 0x0104;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}